author: Weijie Zhang
  email: wez042@ucsd.edu

description: >
  Classifying recipes' popularity level and rating with imbalanced data 
  using RandomForest and BalancedRandomForest. 

# Build settings
theme: minima
plugins:
  - jekyll-remote-theme
  
remote_theme: jekyll/minima
  
